# Generated by Django 4.0.1 on 2022-01-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=70)),
                ('EventDescription', models.TextField()),
                ('poster', models.ImageField(default='media/poster.jpg', upload_to='media')),
                ('EventFrom', models.TimeField(default='00:00:00')),
                ('EventTo', models.TimeField(default='00:00:00')),
                ('EventRegDeadline', models.DateTimeField(default='00:00:00')),
                ('EventHostEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
