# Generated by Django 4.0.1 on 2022-01-24 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=70)),
                ('EventDescription', models.TextField()),
                ('EventFrom', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 4, 28, 64319))),
                ('EventTo', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 4, 28, 64319))),
                ('EventRegDeadline', models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 4, 28, 64319))),
                ('EventHostEmail', models.EmailField(default='', max_length=254)),
                ('EventHostPwd', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParticipantName', models.CharField(max_length=70)),
                ('ParticipantContact', models.CharField(max_length=10)),
                ('ParticipantEvent', models.IntegerField()),
                ('ParticipantEventName', models.CharField(default='', max_length=70)),
                ('ParticipantEmail', models.EmailField(default='', max_length=254)),
                ('ParticipantCount', models.IntegerField(default=1)),
            ],
        ),
    ]
