# Generated by Django 4.0.1 on 2022-01-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventFrom',
        ),
        migrations.RemoveField(
            model_name='event',
            name='EventHostEmail',
        ),
        migrations.RemoveField(
            model_name='event',
            name='EventRegDeadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='EventTo',
        ),
        migrations.RemoveField(
            model_name='event',
            name='poster',
        ),
    ]
