# Generated by Django 4.0.1 on 2022-01-24 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_alter_event_eventfrom_alter_event_eventregdeadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='ParticipantEvent',
            new_name='ParticipantEventID',
        ),
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 15, 31, 74824)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 15, 31, 74824)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 15, 31, 74824)),
        ),
    ]
