# Generated by Django 4.0.1 on 2022-01-21 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_event_eventfrom_event_eventregdeadline_event_eventto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 13, 41, 15, 282979)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 13, 41, 15, 282979)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 13, 41, 15, 282979)),
        ),
    ]
