# Generated by Django 4.0.1 on 2022-01-24 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_alter_event_eventfrom_alter_event_eventregdeadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 24, 16, 678550)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 24, 16, 678550)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 24, 16, 678550)),
        ),
    ]
