# Generated by Django 4.0.1 on 2022-01-21 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_event_eventposter_alter_event_eventfrom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 14, 12, 8, 145727)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventPoster',
            field=models.ImageField(default='poster.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 14, 12, 8, 145727)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 14, 12, 8, 145727)),
        ),
    ]
