# Generated by Django 4.0.1 on 2022-01-24 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_event_eventfrom_alter_event_eventregdeadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ParticipantEvent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_app.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 26, 24, 151067)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 26, 24, 151067)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 26, 24, 151067)),
        ),
    ]
