# Generated by Django 4.0.1 on 2022-01-31 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_participant_participantevent_alter_event_eventfrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='EventVenue',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 22, 30, 6, 128682)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 22, 30, 6, 128682)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 22, 30, 6, 128682)),
        ),
    ]
