# Generated by Django 4.0.1 on 2022-01-22 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_participant_event_eventhostemail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='EventPoster',
        ),
        migrations.AddField(
            model_name='event',
            name='EventHostPwd',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 17, 11, 426692)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 17, 11, 426692)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 23, 3, 17, 11, 426692)),
        ),
    ]
