# Generated by Django 4.0.1 on 2022-01-23 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_remove_event_eventposter_event_eventhostpwd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='Participantpwd',
        ),
        migrations.AddField(
            model_name='participant',
            name='ParticipantCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 49, 47, 406250)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 49, 47, 407251)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 49, 47, 407251)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ParticipantEvent',
            field=models.IntegerField(max_length=3),
        ),
    ]
