# Generated by Django 4.0.1 on 2022-01-23 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0009_remove_participant_participantpwd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventFrom',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 55, 29, 131425)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventRegDeadline',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 55, 29, 131425)),
        ),
        migrations.AlterField(
            model_name='event',
            name='EventTo',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 2, 55, 29, 131425)),
        ),
        migrations.AlterField(
            model_name='participant',
            name='ParticipantEvent',
            field=models.IntegerField(),
        ),
    ]
